name: testVerstka
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  rxdart: ^0.25.0
  connectivity: ^2.0.2
  device_preview: ^0.5.5



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: lib/assets/SFProDisplay-Thin.ttf